server:
    port: 8082
spring:
    application:
        name: userMovieService
    data       :
        mongodb:
            uri: mongodb://localhost:27017/UserMovieDb
eureka:
    client:
        service-url         :
            defaultZone: http://localhost:8761/eureka
        fetch-registry      : true
        register-with-eureka: true